### ISSUE TITLE
现在好像不能显示翻译了

### ISSUE THREAD

**Issue by meteormatt** [rosickey/youdao-firefox#3]
不知道是什么原因
有发音, 但是没有翻译显示
![snap1](https://cloud.githubusercontent.com/assets/424475/3564986/cf7f73ec-0aa1-11e4-9519-62e525101c08.png)

**Comment by meteormatt** [comment]
今天开始又不能用了.
可能是我这里访问Google有流量异常.
![snap1](https://cloud.githubusercontent.com/assets/424475/7195170/dc98c69c-e4ed-11e4-94e3-e5e08c899c5a.png)

http://translate.google.com/translate_a/t?client=j&text=key&sl=en&tl=zh-CN
301到
http://ipv4.google.com/sorry/IndexRedirect?continue=http://translate.google.com/translate_a/t%3Fclient%3Dj%26text%3Dkey%26sl%3Den%26tl%3Dzh-CN&q=CGMSBHTkWLQYwOPBqQUiGQDxp4NL1xaMyaQ4XXKGyA7wFKKfs1G5DmY
然后出了503

**Comment by rosickey** [comment]
google translate 的连接规则变化了吧，

content/youdaotrans.js 222行
var url="http://translate.google.com/translate_a/t?";
var parameters="client=j&text="+text+"&sl="+fasttransk.lfrom.value+"&tl="+fasttransk.lto.value;
gtans.open('GET', url+parameters, true);

应该要改一下了，现在翻译地址的规则是这样的
https://translate.google.com/#en/zh-CN/key

**Comment by meteormatt** [comment]
那就麻烦你再改下了. 谢谢.

**Comment by rosickey** [comment]
![screenshot 2015-07-07 2 36 24](https://cloud.githubusercontent.com/assets/1156906/8540334/4e898288-24b7-11e5-86d2-e72afe5a5d45.png)

链接更新为了国内的youdao，不存在翻墙的问题了

**Comment by meteormatt** [comment]
@rosickey 谢谢了. 等待AMO上的更新.
