### ISSUE TITLE
connection error after updating firefox

### ISSUE THREAD

**Issue by wenzhenl** [rosickey/youdao-firefox#5]
Now I just always get "connection error, please try again".
![screenshot from 2015-08-12 09 18 37](https://cloud.githubusercontent.com/assets/7431540/9229898/3fdd4cf4-40d4-11e5-8532-07c0bac0c489.png)

**Comment by rosickey** [comment]
you use the dev branch or master?

**Comment by wenzhenl** [comment]
I just installed it from Firefox.

Best,

Wenzheng

**Comment by rosickey** [comment]
the version in firefox is use google's translate api, i have not commit update to firefox. i can not endure the review process...

you can download dev branch source code from github, copy the content folder to your firefox extensions folder.
![snip20150813_2](https://cloud.githubusercontent.com/assets/1156906/9240506/d4b31370-4199-11e5-992e-9df71f113ccc.png)

**Comment by wenzhenl** [comment]
Thanks a lot!

Best,

Wenzheng

**Comment by rosickey** [comment]
No thanks.

认识普通话吗？在美国吗？能聊天吗？

**Comment by wenzhenl** [comment]
当然，嗯，是在美国

Best,

Wenzheng

**Comment by rosickey** [comment]
还回国吗？想买个PS4...

**Comment by wenzhenl** [comment]
暑假刚回的国。感觉我们这样在Github上聊天很搞啊。

Best,

Wenzheng

**Comment by rosickey** [comment]
下次回国...有机会留个言...

**Comment by wenzhenl** [comment]
Okay.
