### ISSUE TITLE
v1.1 无法翻译

### ISSUE THREAD

**Issue by yaohunzhanyue** [rosickey/youdao-firefox#6]
显示：
Youdao-Translating 正在工作中…。…。……。…。…。……

等了好几分钟一直无反应，只能点read more

运行环境：firefox 48.0 in linuxmint

**Comment by yaohunzhanyue** [comment]
尝试将branch dev中的content导入extensions失败，请问linux版的firefox该怎么做呢？

**Comment by rosickey** [comment]
将DEV content的内容复制到电脑插件安装目录后，插件会显示不能使用。
解决办法： about:config  下，找到xpinstall.signatures.required 修改为false

**Comment by yaohunzhanyue** [comment]
补充一下
window7下firefox的extions路径：
C:\Users\zyx\AppData\Roaming\Mozilla\Firefox\Profiles\tt4k2woe.default\extensions

ps：firefox从48版本开始无法通过修改xpinstall.signatures.required为false来跳过验证，所以目前48及以上版本无法使用
